# Generated by Django 4.2.1 on 2023-07-05 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propet', '0003_boleta_detalle_boleta'),
    ]

    operations = [
    ]
