# Generated by Django 4.2.1 on 2023-07-06 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propet', '0004_auto_20230704_2305'),
    ]

    operations = [
    ]
