# Generated by Django 4.2.1 on 2023-07-06 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propet', '0005_auto_20230705_2023'),
    ]

    operations = [
    ]
