# Generated by Django 4.2.1 on 2023-07-06 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propet', '0006_auto_20230705_2024'),
    ]

    operations = [
    ]
