# Generated by Django 4.2.1 on 2023-07-06 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propet', '0007_auto_20230705_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_boleta',
            name='estado',
            field=models.CharField(choices=[('procesando', 'Procesando pedido')], default='procesando su compra', max_length=20),
        ),
    ]
