# Generated by Django 4.2.1 on 2023-07-06 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propet', '0009_alter_detalle_boleta_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_boleta',
            name='estado',
            field=models.CharField(default='procesando su compra', max_length=40),
        ),
    ]
