# Generated by Django 4.2.1 on 2023-07-06 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propet', '0010_alter_detalle_boleta_estado'),
    ]

    operations = [
    ]
