# Generated by Django 4.2.1 on 2023-07-06 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propet', '0011_auto_20230705_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_boleta',
            name='estado',
            field=models.CharField(default='procesando su pedido', max_length=40),
        ),
    ]
