# Generated by Django 4.2.1 on 2023-07-06 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('propet', '0012_alter_detalle_boleta_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_boleta',
            name='usuario',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
