# Generated by Django 4.2.1 on 2023-07-06 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propet', '0013_detalle_boleta_usuario'),
    ]

    operations = [
    ]
